# Generated by Django 3.2.4 on 2021-08-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_image', models.ImageField(height_field='100', help_text='student image', upload_to='student_image', width_field='50')),
                ('first_name', models.CharField(help_text='student first name ', max_length=19)),
                ('last_name', models.CharField(help_text='student last name', max_length=19)),
                ('email', models.EmailField(help_text='student email', max_length=254)),
                ('reg_no', models.CharField(help_text='registration number ', max_length=16)),
                ('gadget_brand', models.CharField(help_text='e.g. hp', max_length=15)),
                ('gadget_model', models.CharField(help_text='folio 9470', max_length=15)),
                ('gadget_serial', models.CharField(help_text='CNU4149***', max_length=15)),
                ('gadget_os', models.CharField(choices=[('windows', 'Windows'), ('harmony', 'harmony'), ('ubuntu', 'ubuntu'), ('ios', 'ios'), ('android', 'android'), ('linux', 'linux')], max_length=8)),
                ('leave_time', models.DateTimeField(auto_now=True)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-first_name'],
            },
        ),
    ]
